[project]
name = "math_egarciarey1981"
description = "My first Pip Package"
version = "0.0.1"
requires-python = ">=3.7"

[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.11"
tag_format = "$version"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"